image: node:4.5.0

pipelines:
  branches:
    master:
      - step:
        script:
          - apt-get update
          - npm install -g node-google-apps-script
          - echo $GAPPS_CONFIG > $HOME/.gapps
          - gapps upload