version: 2
jobs:
  build:
    docker:
     - image: circleci/node:7.10.0

    steps:
      - checkout
      - run:
          name: get package list
          command: sudo apt-get update
      - run:
          name: install gapps
          command: npm install -g node-google-apps-script
      - run:
          name: create ".gapps"
          command: echo ${GAPPS_AUTH} > ~/.gapps
      - run:
          name: create "gapps.config.json"
          command: echo ${GAPPS_CONFIG} > gapps.config.json
      - deploy:
          name: deploy master to Google Apps Script
          command: gapps upload